version: '3.8'

services:
  backend:
    build:
      context: ./express-cuda-sp3
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/crud-api
      - JWT_SECRET=25tsgwu36HEGHSG456378@@djks
    networks:
      - app-network
    depends_on:
      mongodb:
        condition: service_healthy

  frontend:
    build:
      context: ./cuda-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - app-network
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: AAAA1234bcde  

networks:
  app-network:

volumes:
  mongodb_data: